"""Neural-network hedge policies.

The policy design follows the direct-policy-search perspective in deep hedging
[Buehler2019]. The Recurrent policy receives the previous hedge position, which
is relevant when transaction costs depend on the size of each trade.
"""
from __future__ import annotations

from typing import Literal
import torch
from torch import nn


class TinyMLP(nn.Module):
    """Small feed-forward network used at one hedge date."""

    def __init__(
        self,
        input_dim: int,
        hidden: int = 15,
        final: Literal["sigmoid", "relu", "linear"] = "sigmoid",
    ):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden),
            nn.ReLU(),
            nn.Linear(hidden, hidden),
            nn.ReLU(),
            nn.Linear(hidden, 1),
        )
        self.final = final

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        y = self.net(x)
        if self.final == "sigmoid":
            # A short European call hedged with stock has a natural range [0, 1].
            return torch.sigmoid(y).squeeze(-1)
        if self.final == "relu":
            return torch.relu(y).squeeze(-1)
        return y.squeeze(-1)


class SimplePolicy(nn.Module):
    """Simple GBM policy using current log-moneyness and time to maturity."""

    uses_extra_state = False

    def __init__(self, cfg, final: str = "sigmoid"):
        super().__init__()
        self.cfg = cfg
        self.nets = nn.ModuleList(
            [TinyMLP(2, cfg.hidden, final=final) for _ in range(cfg.N)]
        )

    def features(self, t: int, S_t: torch.Tensor) -> torch.Tensor:
        tau_fraction = torch.full_like(S_t, (self.cfg.N - t) / self.cfg.N)
        log_moneyness = torch.log(torch.clamp(S_t / self.cfg.K, min=1e-12))
        return torch.stack([log_moneyness, tau_fraction], dim=1)

    def forward_one_step(
        self,
        t: int,
        S_t: torch.Tensor,
        previous_delta: torch.Tensor | None = None,
        extra_state_t: torch.Tensor | None = None,
    ) -> torch.Tensor:
        del previous_delta, extra_state_t
        return self.nets[t](self.features(t, S_t))


class RecurrentPolicy(nn.Module):
    """GBM policy that also observes the previous stock hedge position."""

    uses_extra_state = False

    def __init__(self, cfg, final: str = "sigmoid"):
        super().__init__()
        self.cfg = cfg
        self.nets = nn.ModuleList(
            [TinyMLP(3, cfg.hidden, final=final) for _ in range(cfg.N)]
        )

    def features(
        self,
        t: int,
        S_t: torch.Tensor,
        previous_delta: torch.Tensor,
    ) -> torch.Tensor:
        tau_fraction = torch.full_like(S_t, (self.cfg.N - t) / self.cfg.N)
        log_moneyness = torch.log(torch.clamp(S_t / self.cfg.K, min=1e-12))
        return torch.stack(
            [log_moneyness, tau_fraction, previous_delta], dim=1
        )

    def forward_one_step(
        self,
        t: int,
        S_t: torch.Tensor,
        previous_delta: torch.Tensor,
        extra_state_t: torch.Tensor | None = None,
    ) -> torch.Tensor:
        del extra_state_t
        return self.nets[t](self.features(t, S_t, previous_delta))


class HestonSimplePolicy(nn.Module):
    """Simple Heston-market policy using an observable variance estimate.

    Features
    --------
    ``[log(S_t/K), time_to_maturity/T, sqrt(v_hat_t)/sigma_0]``

    ``v_hat_t`` is an EWMA estimate constructed from observed stock returns. It
    is **not** the latent Heston variance generated by the simulator.
    """

    uses_extra_state = True

    def __init__(self, cfg, final: str = "sigmoid"):
        super().__init__()
        self.cfg = cfg
        self.nets = nn.ModuleList(
            [TinyMLP(3, cfg.hidden, final=final) for _ in range(cfg.N)]
        )

    def features(
        self,
        t: int,
        S_t: torch.Tensor,
        v_hat_t: torch.Tensor,
    ) -> torch.Tensor:
        tau_fraction = torch.full_like(S_t, (self.cfg.N - t) / self.cfg.N)
        log_moneyness = torch.log(torch.clamp(S_t / self.cfg.K, min=1e-12))
        volatility_feature = (
            torch.sqrt(torch.clamp(v_hat_t, min=self.cfg.variance_floor))
            / self.cfg.sigma
        )
        return torch.stack(
            [log_moneyness, tau_fraction, volatility_feature], dim=1
        )

    def forward_one_step(
        self,
        t: int,
        S_t: torch.Tensor,
        previous_delta: torch.Tensor | None = None,
        extra_state_t: torch.Tensor | None = None,
    ) -> torch.Tensor:
        del previous_delta
        if extra_state_t is None:
            raise ValueError(
                "HestonSimplePolicy requires an observable variance estimate."
            )
        return self.nets[t](self.features(t, S_t, extra_state_t))


class HestonRecurrentPolicy(nn.Module):
    """Recurrent Heston-market policy with observable volatility and holdings.

    Features
    --------
    ``[log(S_t/K), time_to_maturity/T, sqrt(v_hat_t)/sigma_0, previous_delta]``
    """

    uses_extra_state = True

    def __init__(self, cfg, final: str = "sigmoid"):
        super().__init__()
        self.cfg = cfg
        self.nets = nn.ModuleList(
            [TinyMLP(4, cfg.hidden, final=final) for _ in range(cfg.N)]
        )

    def features(
        self,
        t: int,
        S_t: torch.Tensor,
        v_hat_t: torch.Tensor,
        previous_delta: torch.Tensor,
    ) -> torch.Tensor:
        tau_fraction = torch.full_like(S_t, (self.cfg.N - t) / self.cfg.N)
        log_moneyness = torch.log(torch.clamp(S_t / self.cfg.K, min=1e-12))
        volatility_feature = (
            torch.sqrt(torch.clamp(v_hat_t, min=self.cfg.variance_floor))
            / self.cfg.sigma
        )
        return torch.stack(
            [
                log_moneyness,
                tau_fraction,
                volatility_feature,
                previous_delta,
            ],
            dim=1,
        )

    def forward_one_step(
        self,
        t: int,
        S_t: torch.Tensor,
        previous_delta: torch.Tensor,
        extra_state_t: torch.Tensor | None = None,
    ) -> torch.Tensor:
        if extra_state_t is None:
            raise ValueError(
                "HestonRecurrentPolicy requires an observable variance estimate."
            )
        return self.nets[t](
            self.features(t, S_t, extra_state_t, previous_delta)
        )
